version: '3.7'

services:
  sample-spring-app:
    image: sample-spring-app:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  prometheus:
    image: prom/prometheus
    depends_on:
      - sample-spring-app
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus

networks:
  monitoring: